name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev liblz4-tool libncurses6 libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3
        mkdir -p $GITHUB_WORKSPACE/toolchains

    - name: Download Toolchains
      run: |
        cd $GITHUB_WORKSPACE/toolchains
        git clone --depth 1 -b main https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 clang
        git clone --depth 1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc64
        git clone --depth 1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc32

    - name: Download Kernel Sources
      run: |
        git clone --depth 1 -b 16.0-raphael https://github.com/crdroidandroid/android_kernel_xiaomi_sm8150 kernel

    - name: Download Kernel Config
      run: |
        git clone https://github.com/qqdasb/crdroid-kernel-raphael-lxc --depth 1
        mkdir kernel/out
        cd kernel
        cp ../crdroid-kernel-raphael-lxc/config out/.config

    - name: Build
      run: |
        CLANG_BIN=$GITHUB_WORKSPACE/toolchains/clang/clang-r530567/bin
        GCC64_BIN=$GITHUB_WORKSPACE/toolchains/gcc64/bin
        GCC32_BIN=$GITHUB_WORKSPACE/toolchains/gcc32/bin
        export PATH=$CLANG_BIN:$GCC64_BIN:$GCC32_BIN:$PATH
        
        cd kernel
        make -j$(nproc --all) O=out \
          ARCH=arm64 \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi- \
          LLVM=1 \
          LLVM_IAS=1 \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip \
          LD=ld.lld \
          Image.gz-dtb

    - name: Pack with AnyKernel
      run: |
        git clone --depth 1 https://github.com/qqdasb/AnyKernel3-raphael.git AnyKernel3
        cp kernel/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        
        cd AnyKernel3
        zip -r ../Kernel.zip *

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Raphael-Kernel
        path: Kernel.zip
        
